version: 2.1
orbs:
  heroku: circleci/heroku@2.0
jobs:
  testing:
    docker:
      - image: shehan97/server-test:latest
        auth:
          username: shehan97
          password: dockershehan1234
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: npm install
      - run:
          name: Test the app
          command: npm test
  deploy:
    executor: heroku/default
    steps:
      - checkout
      - heroku/install
      - run:
          command: >
            echo "The command above installs Heroku, the command below deploys.
            What you do in between is up to you!"
      - heroku/deploy-via-git
      - run:
          name: Check deployment status
          command: |
            heroku ps --app server-test97
workflows:
  heroku_deploy:
    jobs:
      - testing
      - deploy:
          requires:
            - testing